/*
 *  Projet AngryBirds
 *  DUT Informatique - 2e
 */
package angrybirds.debugbox;

import angrybirds.Game;
import angrybirds.Tools;
import angrybirds.structures.Vector2d;
import angrybirds.trajectories.curves.LinearMovement;
import angrybirds.trajectories.MovementApplyer;
import angrybirds.trajectories.curves.ParabolicMovement;
import java.util.Observable;
import java.util.Observer;
import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author Pierre
 */
public class DebugBox extends javax.swing.JFrame implements Observer {

    private final DebugBoxModel model;
    private final DebugBoxController debugBoxController;
    private final Game game;

    private final DefaultComboBoxModel moves = new DefaultComboBoxModel<>();

    /**
     * Creates new form DebugBox
     *
     * @param model
     * @param debugBoxController
     * @param game
     */
    public DebugBox(DebugBoxModel model, DebugBoxController debugBoxController, Game game) {
        this.model = model;
        this.debugBoxController = debugBoxController;
        this.game = game;

        moves.addElement("parabolic");
        moves.addElement("linear");

        initComponents();
    }

    public DebugBoxController getDebugBoxController() {
        return debugBoxController;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        refreshIte = new javax.swing.JLabel();
        resetScene = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox();
        execBird = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        birdX = new javax.swing.JTextField();
        birdY = new javax.swing.JTextField();
        applyPosition = new javax.swing.JButton();
        length = new javax.swing.JTextField();
        width = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        blockGame = new javax.swing.JToggleButton();
        parameterMovement = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("DebugBox");

        refreshIte.setText("Refresh #");

        resetScene.setText("Reset scene");
        resetScene.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetSceneActionPerformed(evt);
            }
        });

        jComboBox1.setModel(moves);
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        execBird.setText("exec on bird");
        execBird.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                execBirdActionPerformed(evt);
            }
        });

        birdX.setText("coordX");

        birdY.setText("coordY");

        applyPosition.setText("Apply");
        applyPosition.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                applyPositionActionPerformed(evt);
            }
        });

        length.setText("length");

        width.setText("width");
        width.setToolTipText("");

        blockGame.setText("Block game");
        blockGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                blockGameActionPerformed(evt);
            }
        });

        parameterMovement.setText("-0.005 3 -1 8 2");
        parameterMovement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                parameterMovementActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(blockGame, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(refreshIte)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(resetScene, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(24, 24, 24)
                        .addComponent(execBird))
                    .addComponent(applyPosition, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(length, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(birdX, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(birdY)
                            .addComponent(width, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(parameterMovement))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(refreshIte)
                .addGap(18, 18, 18)
                .addComponent(resetScene)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(execBird))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(parameterMovement, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(birdX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(birdY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(length, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(width, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(applyPosition)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(blockGame)
                .addGap(32, 32, 32))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void resetSceneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetSceneActionPerformed
        game.resetScene();
    }//GEN-LAST:event_resetSceneActionPerformed

    private void applyPositionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_applyPositionActionPerformed
        // have to send to controller that have been updated
        debugBoxController.updatePosition(new Vector2d(
                Double.parseDouble(birdX.getText()),
                Double.parseDouble(birdY.getText()),
                Double.parseDouble(length.getText()),
                Double.parseDouble(width.getText()))
        );
    }//GEN-LAST:event_applyPositionActionPerformed

    private void blockGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_blockGameActionPerformed
        Game.BLOCK_STATUS = !Game.BLOCK_STATUS;
    }//GEN-LAST:event_blockGameActionPerformed

    /**
     * Execute a movement
     *
     * @param evt
     */
    private void execBirdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_execBirdActionPerformed

        if (moves.getSelectedItem().toString().equals("linear")) {
            
            LinearMovement mvt = new LinearMovement(-3, 0, 2);
            MovementApplyer mvtAppl = new MovementApplyer(mvt,
                    game.getBird().getModel() // give the model
            );
            mvt.setMvtApplyer(mvtAppl);
            
            game.getBird().getController().addMovement(mvtAppl);
            Tools.debug("Apply linear movement");
        } // PARABOLIC
        else {
            ParabolicMovement mvt = new ParabolicMovement(parameterMovement.getText());
            MovementApplyer mvtApplyer = new MovementApplyer(
                    mvt, // give parameters
                    game.getBird().getModel() // give the model
            );
            mvt.setMvtApplyer(mvtApplyer);
            game.getBird().getController().addMovement(mvtApplyer);
            
            
            Tools.debug("Apply parabolic movement");
        }
    }//GEN-LAST:event_execBirdActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void parameterMovementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_parameterMovementActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_parameterMovementActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton applyPosition;
    private javax.swing.JTextField birdX;
    private javax.swing.JTextField birdY;
    private javax.swing.JToggleButton blockGame;
    private javax.swing.JButton execBird;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField length;
    private javax.swing.JTextField parameterMovement;
    private javax.swing.JLabel refreshIte;
    private javax.swing.JButton resetScene;
    private javax.swing.JTextField width;
    // End of variables declaration//GEN-END:variables

    @Override
    public void update(Observable o, Object arg) {
        if (o instanceof DebugBoxModel) {
            DebugBoxModel m = ((DebugBoxModel) o);
            refreshIte.setText("Refresh #" + m.getRefresh());

            // Recup bird
            Vector2d position = game.getBird().getModel().getPosition();
            birdX.setText(position.getX() + "");
            birdY.setText(position.getY() + "");
            length.setText(position.getLength() + "");
            width.setText(position.getWidth() + "");
        }
    }
}
